api/urls.py
from django.urls import path, re_path

from .views import *

urlpatterns = [
    re_path(r'model/(?:(?P<action>\w+)/)?', ModelApiView.as_view()),
    path('presensi/', PresensiApiView.as_view()),
    re_path(r'pegawai/(?:(?P<pk>\d+)/)?', PegawaiApiView.as_view()),
    # path('<str:nama>/', PegawaiDetailApiView.as_view()),
    # path('jabatan/', JabatanApiView.as_view(), name='jabatan_api'),
    # path('jabatan/<int:jabatan_id>/', JabatanDetailApiView.as_view()),
]

web/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/forms.py
from django import forms

from home.models import *

class LoginForm(forms.Form):
    username = forms.CharField(
        widget= forms.TextInput(
            attrs= {
                'placeholder': 'Username',
                'class': 'form-control'
            }
        )
    )
    password = forms.CharField(
        widget= forms.PasswordInput(
            attrs= {
                'placeholder': 'Password',
                'class': 'form-control'
            }
        )
    )

class PegawaiForm(forms.ModelForm):
    nip = forms.CharField(
        label='NIP/NIK',
        widget= forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Masukkan NIP/NIK'
            }
        )
    )
    nama = forms.CharField(
        label='Nama Pegawai',
        widget= forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Masukkan Nama'
            }
        )
    )
    nohp = forms.CharField(
        max_length=13,
        label="Nomor Handphone",
        widget= forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Masukkan No HP'
            }
        )
    )
    foto = forms.ImageField(
        required=False,
        label="Foto Wajah",
        widget= forms.ClearableFileInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Masukkan No HP',
                'accept': 'image/*',
                'multiple': True
            }
        )
    )
    jabatan = forms.ModelChoiceField(
        queryset=Jabatan.objects.all(),
        widget= forms.Select(
            attrs={
                'class': 'form-control',
            }
        ),
    )
    shift = forms.ModelChoiceField(
        queryset=Shift.objects.all(),
        widget= forms.Select(
            attrs={
                'class': 'form-control',
            }
        ), 
    )

    class Meta:
        model = Pegawai
        fields = ['nip', 'nama', 'nohp', 'jabatan', 'shift', 'foto', ]

class JabatanForm(forms.ModelForm):
    nama = forms.CharField(
        label='Nama Jabatan',
        widget= forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    class Meta:
        model = Jabatan
        fields = ['nama',]

class ShiftForm(forms.ModelForm):
    masuk = forms.TimeField(
        label='Jam Masuk',
        widget=forms.TimeInput(
            attrs= {
                'class': 'form-control',
                'type': 'time',
            }
        )
    )
    pulang = forms.TimeField(
        label='Jam Pulang',
        widget=forms.TimeInput(
            attrs= {
                'class': 'form-control',
                'type': 'time',
            }
        )
    )
    class Meta:
        model = Shift
        fields = ['masuk', 'pulang',]

templates/base-full.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Smart Attendace Face Recognition - {% block title %}{% endblock %}</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'vendor/nucleo/css/nucleo.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" type="text/css">
    <!-- Argon CSS -->
    <link rel="stylesheet" href="{% static 'css/argon.css' %}?v=1.2.0" type="text/css">

    <!-- Specific CSS goes HERE -->
    {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="bg-default">

    <div class="main-content">
        <nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
            <div class="container">
                <a class="navbar-brand" href="/">
                    <img src="{% static 'img/logo.png' %}" alt="Argon Design - Template Starter Logo.">
                </a>
                <ul class="navbar-nav align-items-lg-center ml-lg-auto">
                    <li class="nav-item d-lg-block ml-lg-4">
                        <a href="/" class="btn btn-neutral btn-icon">
                            <span class="nav-link-inner--text">Home</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <!-- Header -->
        <div class="header bg-gradient-primary py-7 py-lg-8">
            <div class="container">
                <div class="header-body text-center mb-7">
                    <div class="row justify-content-center">
                        <div class="col-lg-5 col-md-6">
                            <h1 class="text-white">
                                Face Recognition
                            </h1>
                            <p class="text-lead text-light">
                                Sistem pengelolaan presensi Face Recognition
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="separator separator-bottom separator-skew zindex-100">
                <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1"
                    xmlns="http://www.w3.org/2000/svg">
                    <polygon class="fill-default" points="2560 0 2560 100 0 100"></polygon>
                </svg>
            </div>
        </div>
        {% block content %}{% endblock content %}
    </div>

    {% include "includes/scripts.html" %}

    <!-- Specific JS goes HERE -->
    {% block javascripts %}{% endblock javascripts %}

</body>

</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Smart Attendace Face Recognition - {% block title %}{% endblock %}</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'vendor/nucleo/css/nucleo.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'vendor/@fortawesome/fontawesome-free/css/all.min.css' %}" type="text/css">
    <link type="text/css" href="{% static 'vendor/notyf/notyf.min.css' %}" rel="stylesheet">
    <!-- Argon CSS -->
    <link rel="stylesheet" href="/static/css/argon.css?v=1.2.0" type="text/css">

    <!-- Specific CSS goes HERE -->
    {% block stylesheets %}{% endblock stylesheets %}
</head>

<body class="">
    {% include "includes/sidenav.html" %}
    <div class="main-content" id="panel">
        <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    {% block breadcrumb %}{% endblock breadcrumb %}
                    <!-- Navbar links -->
                    <ul class="navbar-nav align-items-center ml-md-auto">
                        <li class="nav-item d-xl-none">
                            <!-- Sidenav toggler -->
                            <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin"
                                data-target="#sidenav-main">
                                <div class="sidenav-toggler-inner">
                                    <i class="sidenav-toggler-line"></i>
                                    <i class="sidenav-toggler-line"></i>
                                    <i class="sidenav-toggler-line"></i>
                                </div>
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav align-items-center ml-auto ml-md-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false">
                                <div class="media align-items-center">
                                    <span class="avatar avatar-sm rounded-circle">
                                        <i class="fa fa-user"></i>
                                    </span>
                                    <div class="media-body ml-2 d-none d-lg-block">
                                        <span class="mb-0 text-sm  font-weight-bold">
                                            {{ request.user.username }}
                                        </span>
                                    </div>
                                </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right ">
                                <a href="{% url 'logout' %}" class="dropdown-item">
                                    <i class="ni ni-user-run"></i>
                                    <span>Logout</span>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div> 
        </nav>

        {% block content %}{% endblock content %}

        <!-- Modal Content -->
        <div class="modal fade" id="modal-system" tabindex="-1" role="dialog" aria-labelledby="modal-system"
            aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content"></div>
            </div>
        </div>
        <!-- End of Modal Content -->

    </div>
    {% include "includes/scripts.html" %}
    <!-- Specific JS goes HERE -->
    {% block javascripts %}{% endblock javascripts %}
    <script>
        {% if messages %}
            {% for message in messages %}
                notification['{{ message.tags }}']("<p>" + '{{ message|capfirst }}' + "</p>");
            {% endfor %}
        {% endif %}
    </script>
    
</body>

</html>

templates/basis.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock title %}
    </title>
</head>
<body>
    <ul>
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'login' %}">Login</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
        <li><a href="{% url 'dashboard' %}">Dashboard</a></li>
    </ul>
    {% block content %}{% endblock content %}
</body>
</html>

templates/index.html
{% extends 'basis.html' %}

{% block title %}
Dashboard
{% endblock title %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="id_foto">Foto Wajah:</label>
    <input type="file" name="foto" class="form-control" id="id_foto" required>
    <input type="submit">
</form>

{% endblock content %}
